package com.mannvaasam.controller;
import com.mannvaasam.model.*; import com.mannvaasam.repo.*; import com.mannvaasam.service.CurrentUserService; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.math.*; import java.util.*;
@RestController @RequestMapping("/api/sellers/products") @PreAuthorize("hasRole('SELLER')")
public class SellerProductController {
 final ProductRepository products; final CategoryRepository cats; final CurrentUserService current;
 public SellerProductController(ProductRepository p,CategoryRepository c,CurrentUserService u){products=p;cats=c;current=u;}
 @GetMapping public List<Product> all(){return products.findBySeller(current.get());}
 @PostMapping public Product create(@RequestBody Map<String,Object> b){Product p=new Product();p.name=(String)b.get("name");p.description=(String)b.get("description");p.price=new BigDecimal(String.valueOf(b.get("price")));p.unit=(String)b.get("unit");p.stock=((Number)b.getOrDefault("stock",0)).intValue();p.imageUrl=(String)b.get("imageUrl");p.seller=current.get();Long cid=((Number)b.get("categoryId")).longValue();p.category=cats.findById(cid).orElseThrow(()->new IllegalArgumentException("Category not found"));return products.save(p);}
 @PutMapping("/{id}") public Product update(@PathVariable Long id,@RequestBody Map<String,Object> b){Product p=products.findById(id).orElseThrow(()->new IllegalArgumentException("Product not found"));if(!p.seller.id.equals(current.get().id))throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.FORBIDDEN,"Not your product");if(b.containsKey("name"))p.name=(String)b.get("name");if(b.containsKey("description"))p.description=(String)b.get("description");if(b.containsKey("price"))p.price=new BigDecimal(String.valueOf(b.get("price")));if(b.containsKey("unit"))p.unit=(String)b.get("unit");if(b.containsKey("stock"))p.stock=((Number)b.get("stock")).intValue();if(b.containsKey("imageUrl"))p.imageUrl=(String)b.get("imageUrl");if(b.containsKey("active"))p.active=(Boolean)b.get("active");return products.save(p);}
 @DeleteMapping("/{id}") public Map<String,String> deactivate(@PathVariable Long id){Product p=products.findById(id).orElseThrow(()->new IllegalArgumentException("Product not found"));if(!p.seller.id.equals(current.get().id))throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.FORBIDDEN,"Not your product");p.active=false;products.save(p);return Map.of("message","Product deactivated");}
}