package com.mannvaasam.service;
import com.mannvaasam.model.*; import com.mannvaasam.repo.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*;
@Service public class CartService { final CartRepository carts; final ProductRepository products; final CurrentUserService current;
public CartService(CartRepository c,ProductRepository p,CurrentUserService u){carts=c;products=p;current=u;}
@Transactional public Cart get(){User u=current.get(); return carts.findByUser(u).orElseGet(()->{Cart c=new Cart();c.user=u;return carts.save(c);});}
@Transactional public Cart add(Long productId,int qty){if(qty<1)throw new IllegalArgumentException("Quantity must be at least 1");Cart c=get();Product p=products.findById(productId).orElseThrow(()->new IllegalArgumentException("Product not found"));if(!p.active||p.stock==null)throw new IllegalArgumentException("Product unavailable");if(qty>p.stock)throw new IllegalArgumentException("Insufficient stock");if(!c.items.isEmpty()&&c.items.stream().anyMatch(i->!i.product.seller.id.equals(p.seller.id)))throw new IllegalArgumentException("Cart can contain products from one seller at a time");CartItem i=c.items.stream().filter(x->x.product.id.equals(productId)).findFirst().orElse(null);if(i==null){i=new CartItem();i.cart=c;i.product=p;i.quantity=qty;i.priceSnapshot=p.price;c.items.add(i);}else{int n=i.quantity+qty;if(n>p.stock)throw new IllegalArgumentException("Insufficient stock");i.quantity=n;i.priceSnapshot=p.price;}c.updatedAt=java.time.Instant.now();return carts.save(c);}
@Transactional public Cart update(Long itemId,int qty){Cart c=get();CartItem i=c.items.stream().filter(x->x.id.equals(itemId)).findFirst().orElseThrow(()->new IllegalArgumentException("Cart item not found"));if(qty<1)throw new IllegalArgumentException("Quantity must be at least 1");if(qty>i.product.stock)throw new IllegalArgumentException("Insufficient stock");i.quantity=qty;i.priceSnapshot=i.product.price;return carts.save(c);}
@Transactional public Cart remove(Long itemId){Cart c=get();c.items.removeIf(i->i.id.equals(itemId));return carts.save(c);}
@Transactional public void clear(){Cart c=get();c.items.clear();carts.save(c);}
}