package com.mannvaasam.service;
import com.mannvaasam.model.*; import com.mannvaasam.repo.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class OrderService { final OrderRepository orders; final CartService cartService; final AddressRepository addresses; final ProductRepository products; final PaymentRepository payments; final OrderStatusHistoryRepository history; final CurrentUserService current; final DeliveryService delivery;
public OrderService(OrderRepository o,CartService c,AddressRepository a,ProductRepository p,PaymentRepository pay,OrderStatusHistoryRepository h,CurrentUserService u,DeliveryService d){orders=o;cartService=c;addresses=a;products=p;payments=pay;history=h;current=u;delivery=d;}
@Transactional public List<Order> myOrders(){return orders.findByBuyerOrderByCreatedAtDesc(current.get());}
@Transactional public Order checkout(Long addressId,String paymentMethod){User buyer=current.get(); if(!"COD".equalsIgnoreCase(paymentMethod))throw new IllegalArgumentException("Only COD is currently enabled"); Address a=addresses.findByIdAndUser(addressId,buyer).orElseThrow(()->new IllegalArgumentException("Delivery address not found")); Cart c=cartService.get();if(c.items.isEmpty())throw new IllegalArgumentException("Cart is empty");User seller=c.items.get(0).product.seller;for(CartItem i:c.items){Product p=products.findById(i.product.id).orElseThrow();if(!p.active||p.stock<i.quantity)throw new IllegalArgumentException("Stock unavailable for "+p.name);if(!p.seller.id.equals(seller.id))throw new IllegalArgumentException("Cart contains multiple sellers");if(!delivery.deliverable(p,a))throw new IllegalArgumentException("Product '"+p.name+"' is currently unavailable in your delivery area");}
Order o=new Order();o.orderNumber="MV-"+System.currentTimeMillis()+"-"+(1000+(int)(Math.random()*9000));o.buyer=buyer;o.seller=seller;o.paymentMethod=PaymentMethod.COD;o.paymentStatus=PaymentStatus.NOT_REQUIRED;o.shippingAddress=a.addressLine;o.city=a.city;o.state=a.state;o.pincode=a.pincode;o.latitude=a.latitude;o.longitude=a.longitude;o.estimatedDeliveryDays=3;
BigDecimal sub=BigDecimal.ZERO;for(CartItem ci:c.items){Product p=ci.product;p.stock-=ci.quantity;OrderItem oi=new OrderItem();oi.order=o;oi.product=p;oi.productName=p.name;oi.unit=p.unit;oi.quantity=ci.quantity;oi.unitPrice=p.price;oi.subtotal=p.price.multiply(BigDecimal.valueOf(ci.quantity));sub=sub.add(oi.subtotal);o.items.add(oi);}o.subtotal=sub;o.deliveryCharge=BigDecimal.ZERO;o.total=sub;Order saved=orders.save(o);OrderStatusHistory h=new OrderStatusHistory();h.order=saved;h.status=OrderStatus.PLACED;h.changedBy=buyer.email;h.note="Order placed with COD";history.save(h);Payment pay=new Payment();pay.order=saved;pay.method=PaymentMethod.COD;pay.status=PaymentStatus.NOT_REQUIRED;pay.amount=sub;payments.save(pay);cartService.clear();return saved;}
@Transactional public Order getBuyer(Long id){return orders.findByIdAndBuyer(id,current.get()).orElseThrow(()->new IllegalArgumentException("Order not found"));}
@Transactional public Order cancel(Long id){Order o=getBuyer(id);if(!(o.status==OrderStatus.PLACED||o.status==OrderStatus.CONFIRMED))throw new IllegalArgumentException("Order cannot be cancelled now");o.status=OrderStatus.CANCELLED;o.updatedAt=Instant.now();for(OrderItem i:o.items){Product p=products.findById(i.product.id).orElse(null);if(p!=null)p.stock+=i.quantity;}orders.save(o);OrderStatusHistory h=new OrderStatusHistory();h.order=o;h.status=o.status;h.changedBy=current.get().email;h.note="Cancelled by buyer";history.save(h);return o;}
@Transactional public Order updateSeller(Long id,OrderStatus status){Order o=orders.findByIdAndSeller(id,current.get()).orElseThrow(()->new IllegalArgumentException("Order not found"));if(status==OrderStatus.PLACED||status==OrderStatus.CANCELLED)throw new IllegalArgumentException("Invalid seller status transition");o.status=status;o.updatedAt=Instant.now();orders.save(o);OrderStatusHistory h=new OrderStatusHistory();h.order=o;h.status=status;h.changedBy=current.get().email;history.save(h);return o;}
public String print(Long id){Order o=getBuyer(id);return html(o);} private String esc(String s){return s==null?"":s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace(""","&quot;");}
private String html(Order o){StringBuilder b=new StringBuilder("<!doctype html><html><head><meta charset='UTF-8'><title>MannVaasam "+esc(o.orderNumber)+"</title><style>@page{size:A4;margin:16mm}body{font-family:Arial;color:#183b2a}h1{margin:0}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border:1px solid #ddd;padding:8px;text-align:left}.right{text-align:right}.total{font-size:18px;font-weight:bold}</style></head><body><h1>MannVaasam</h1><p>Order: "+esc(o.orderNumber)+"<br>Status: "+o.status+"<br>Payment: "+o.paymentMethod+" / "+o.paymentStatus+"</p><h3>Delivery</h3><p>"+esc(o.shippingAddress)+", "+esc(o.city)+", "+esc(o.state)+" - "+esc(o.pincode)+"</p><table><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Price</th><th>Subtotal</th></tr>");for(OrderItem i:o.items)b.append("<tr><td>"+esc(i.productName)+"</td><td>"+i.quantity+"</td><td>"+esc(i.unit)+"</td><td>"+i.unitPrice+"</td><td>"+i.subtotal+"</td></tr>");b.append("</table><p class='right'>Subtotal: ₹"+o.subtotal+"<br>Delivery: ₹"+o.deliveryCharge+"<br><span class='total'>Total: ₹"+o.total+"</span></p><p>Estimated delivery: "+o.estimatedDeliveryDays+" days</p><script>window.print()</script></body></html>");return b.toString();}}
